project:
  type: website
  output-dir: docs

website:
  title: "MedEd-Resources by PrabPrime"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: 2025_authentic.qmd
        text: slides

format:
  html:
    theme: cosmo
    mainfont: arial
    fontsize: 1.5rem
    monofont: courier new
    css: styles.css
    toc: true
    toc-depth: 0
    toc-title: "Outline"
    lof: true
    lot: true
    
  pdf:
    toc: true
    toc-depth: 1
    toc-title: "Outline"
    lof: true
    lot: true

editor: visual

