project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - blog.qmd
    - courses/shee/sharing/main_sharing.qmd
    - courses/shee/tailor/main_tailor.qmd
    # - courses/shee/workshop/main_workshop.qmd
  resources:
    - _about/IMG_9039Jn.jpg
    - courses/archive/_resources/
    
website:
  title: "P-MAPR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Ed Blog
      - text: Slides
        menu:
          - sidebar:shr
          - sidebar:tlr
          # - sidebar:wsh
      
  sidebar:
    - id: shr
      title: "SHEE Sharing"
      style: "docked"
      # foreground: '#BC0031'
      background: light
      collapse-level: 2
      contents:
        - courses/shee/sharing/main_sharing.qmd
    - id: tlr
      title: "Tailor Slides"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - courses/shee/tailor/main_tailor.qmd
    # - id: wsh
    #   title: "Workshop Slides"
    #   style: "docked"
    #   background: light
    #   collapse-level: 2
    #   contents:
    #     - courses/shee/workshop/main_workshop.qmd
        
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-location: left
    linkcolor: '#BC0031'
    df-print: kable
    smooth-scroll: true
    link-external-newwindow: true
    css: styles.css
  revealjs:
    smaller: false
    linkcolor: '#BC0031'
    transition: slide
    background-transition: fade
    theme: white
    slide-number: true
    touch: true
    output-ext: slide.html

html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
  
editor: visual

