---
title: "Summary of Foundation of Assessment"
date: 2025-04-04
  date-format: "MMM D, YYYY"
date-modified: 2025-04-03
format: 
  revealjs:
    slide-number: true
    css: ~/Documents/Work/Project/quarto_presentation/education/styles.css
    chalkboard: 
      buttons: false
    preview-links: auto
    footer: 'Assessment workshop for clinical teacher'
editor: visual
bibliography: /Users/prabprime/Documents/References/My Library.bib
---

## Schedule

::: left-align-table
+---------------+-------------------------------+----------------------------------+
|               | Topic                         | Key-message                      |
+===============+===============================+==================================+
| 0830 - 1015   | Basic Principle of assessment | -   Test-enhanced learning       |
|               |                               |                                  |
|               |                               | -   Consensus of Good Assessment |
+---------------+-------------------------------+----------------------------------+
| 1030 - 1200   | Standard setting              | -   Test-centered methods        |
|               |                               | -   Examinee-centerd methods     |
|               |                               | -   MPL                          |
+---------------+-------------------------------+----------------------------------+
| 1300 - 1430   | Item analysis                 |                                  |
+---------------+-------------------------------+----------------------------------+
| 1445 - 1545   | Programmatic assessment       |                                  |
+---------------+-------------------------------+----------------------------------+
| 1545 - 1600   | Summary                       |                                  |
+---------------+-------------------------------+----------------------------------+
:::

## Consensus of Good Assessment

[1.  Validity]{.fragment style="font-weight:bold;background-color:#ccddeb;"}

2.  Reliability

3.  Equivalence and Feasibility

4.  Educational effect

5.  Catalytic effect

6.  Acceptability

::: footnote
@2018_norcini.etal
:::

## Posttest Examination

```{r tbl-planets, echo=FALSE}
# Table of astronomical objects
#| label: tbl-planets
#| tbl-cap: Astronomical object
library(knitr)

table <- data.frame(
  `Astronomical object` = c("Sun", "Earth", "Moon", "Mars"),
  `R (km)` = c("696,000", "6,371", "1,737", "3,390"),
  `mass (kg)` = c(1.989e30, 5.972e24, 7.34e22, 6.39e23)
)

kable(table, caption = "Astronomical object")
```

## Reflection time

+ What is happening?

+ How what happening resonate with me?

+ How should I improve?

## Bullets

When you click the **Render** button a document will be generated that includes:

::: incremental
-   Content authored with markdown

-   Output from executable code
:::

## Check Reliability

### Cronbach's Alpha {.kanit-bold .math-slide}

$$
\alpha = \frac{n}{n - 1} \left( 1 - \frac{ \sum \sigma_{x_i}^2 }{ \sigma_x^2 } \right)
$$ {#eq-cronbach-alpha}

-   $n$ = number of items
-   $\sigma_{x_i}$ = variance of the item
-   $\sigma_x$ = variance of the test

## 

| Cronbach’s alpha (α) | Qualitative Descriptor |
|----------------------|------------------------|
| .95–1.00             | Excellent              |
| .90–.94              | Great                  |
| .80–.89              | Good                   |
| .70–.79              | Acceptable             |
| .60–.69              | Questionable           |
| .00–.59              | Unacceptable           |
as use in @eq-cronbach-alpha

## Improving Reliability

### How many more items you need to achieve your desired reliability - *Spearman-Brown* Formula {.kanit-bold .math-slide}

$$
r_k = \dfrac{k r_1}{1 + (k - 1) r_1}
$$

-   $k$ = factor by which test length is changed

-   $r_{k}$ = reliability of a test “k” times long

-   $r_1$ = reliability of the original test

## Method

### Ebel's Method {#ebel}

360 degree evaluation

> *Thinking Block* Should we get rid of easy and non-essential?

## References

::: {#refs}
:::
