---
title: "MedEd conference"
format: html
---

1.  **AAMC – Learn Serve Lead 2025**

    Conference Dates: November 1–5, 2025

    Location: San Antonio, Texas, USA

    Abstract Deadline: December 2, 2024, at 11:59 PM PST


2.  **APMEC 2026 – Asia Pacific Medical Education Conference**

    Conference Dates: January 21–25, 2026

    Location: China

    Abstract Deadline: June 4, 2025

    Source: <https://inetapps.nus.edu.sg/apmec/abstract/>

3.  **Ottawa Conference 2026**

    Conference Dates:9-10 March 2026

    Location: University of Illinois Chicago, USA

    Abstract Deadline: Expected around August 2025

    Source: University of Saskatchewan MedEd Conference Listings​ 

4.  **TMEC 2026 – Thai Medical Education Conference**

    Conference Dates: February 25–27, 2026

    Location: Phisanulok, Thailand

    Abstract Deadline: Around November, 2025

    Source: TMEC 2026

5. **ICAM 2025 – International Congress on Academic Medicine**

         
    Conference Dates: April 3–6, 2025
    
    Location: Halifax, Nova Scotia, Canada
    
    Abstract Deadline: Closed (was October 4, 2024)
    
    Source: ICAM Abstracts 2025


6. **AMEE 2025 – Association for Medical Education in Europe**

    Conference Dates: August 23–27, 2025

    Location: Barcelona, Spain

    Abstract Deadlines:
    
    Short Communication, ePoster, Fringe, PechaKucha, Point of View, Workshops: January 29, 2025
    
    CPD, Doctoral Reports, Patil Teaching Innovation Awards, Research Papers: October 30, 2024
    
    Pre-conference Workshops and Symposia: October 23, 2024

    Source: 

ICAM 2025 – International Congress on Academic Medicine

    Conference Dates: April 3–6, 2025

    Location: Halifax, Nova Scotia, Canada

    Abstract Deadline: Closed (was October 4, 2024)

    Source: ICAM Abstracts 2025
```

https://inetapps.nus.edu.sg/apmec/abstract/
