---
title: "Generation Engagement"
subtitle: "How Should We Teach the Next Generation of Medical Students?"
date: "4 April 2025"
date-format: long # or date-format: "MMM D, YYYY"
format: 
  revealjs:
    slide-number: true
    preview-links: auto
    footer: 'Generation Engagement'
    output-ext: slide.html
  
editor: visual
bibliography: /Users/prabprime/Documents/References/My Library.bib
---

## Outline

-   engagement

-   curiosity

-   listen and understand

## Curiosity

-   How what happening resonate with me?

-   How should I improve?

## Bullets

When you click the **Render** button a document will be generated that includes:

::: incremental
-   Content authored with markdown

-   Output from executable code
:::

## Check Reliability

### Cronbach's Alpha {.kanit-bold .math-slide}

$$
\alpha = \frac{n}{n - 1} \left( 1 - \frac{ \sum \sigma_{x_i}^2 }{ \sigma_x^2 } \right)
$$ {#eq-cronbach-alpha}

-   $n$ = number of items
-   $\sigma_{x_i}$ = variance of the item
-   $\sigma_x$ = variance of the test

## Cronbach's alpha interpretation

| Cronbach’s alpha (α) | Qualitative Descriptor |
|----------------------|------------------------|
| .95–1.00             | Excellent              |
| .90–.94              | Great                  |
| .80–.89              | Good                   |
| .70–.79              | Acceptable             |
| .60–.69              | Questionable           |
| .00–.59              | Unacceptable           |

as use in @eq-cronbach-alpha

## Improving Reliability

### How many more items you need to achieve your desired reliability - *Spearman-Brown* Formula {.kanit-bold .math-slide}

$$
r_k = \dfrac{k r_1}{1 + (k - 1) r_1}
$$

-   $k$ = factor by which test length is changed

-   $r_{k}$ = reliability of a test “k” times long

-   $r_1$ = reliability of the original test

## Method

### Ebel's Method {#ebel}

360 degree evaluation

> *Thinking Block* Should we get rid of easy and non-essential?

## References

::: {#refs}
:::
